# fly.toml app configuration file generated for nithyananda-ask on 2025-10-07T21:02:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nithyananda-ask'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
