/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    ecitizen: Ecitizen;
    categories: Category;
    videos: Video;
    'live-streams': LiveStream;
    'live-chat': LiveChat;
    'live-stream-views': LiveStreamView;
    transcripts: Transcript;
    'transcript-segments': TranscriptSegment;
    'audio-chunks': AudioChunk;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    ecitizen: EcitizenSelect<false> | EcitizenSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'live-streams': LiveStreamsSelect<false> | LiveStreamsSelect<true>;
    'live-chat': LiveChatSelect<false> | LiveChatSelect<true>;
    'live-stream-views': LiveStreamViewsSelect<false> | LiveStreamViewsSelect<true>;
    transcripts: TranscriptsSelect<false> | TranscriptsSelect<true>;
    'transcript-segments': TranscriptSegmentsSelect<false> | TranscriptSegmentsSelect<true>;
    'audio-chunks': AudioChunksSelect<false> | AudioChunksSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Registered e-citizens allowed to participate in live chat
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecitizen".
 */
export interface Ecitizen {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  videoId: string;
  title: string;
  description?: string | null;
  duration?: string | null;
  date?: string | null;
  category: (number | Category)[];
  /**
   * Optional. Defaults to common resolutions.
   */
  resolutions?: ('1080p' | '720p' | '480p' | '360p' | '240p')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-streams".
 */
export interface LiveStream {
  id: number;
  /**
   * Unique identifier for this stream. Use this as your stream key in OBS/streaming software.
   */
  streamKey: string;
  title: string;
  description?: string | null;
  date: string;
  /**
   * Actual live start time; used as time zero for transcripts.
   */
  startedAt?: string | null;
  visibility: 'public' | 'private';
  /**
   * Current status of the stream (controlled by Start/Stop buttons)
   */
  status: 'idle' | 'live' | 'ending' | 'ended';
  /**
   * Progress details during graceful shutdown
   */
  endingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Enable live transcription for this stream.
   */
  transcriptionEnabled?: boolean | null;
  /**
   * Language code for live transcription (e.g. en, ta).
   */
  transcriptionLanguage?: string | null;
  /**
   * Target languages for live translation (e.g. ta, hi, fr). Leave empty to disable translation.
   */
  translationLanguages?: string[] | null;
  /**
   * Optional RTMP source URL. Leave empty if streaming directly to this server.
   */
  rtmpUrl?: string | null;
  /**
   * HLS master playlist URL (generated automatically)
   */
  masterPlaylistUrl?: string | null;
  /**
   * Thumbnail URL (uploaded via the thumbnail uploader below)
   */
  thumbnailUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Live chat messages for streams
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-chat".
 */
export interface LiveChat {
  id: number;
  /**
   * Message content (max 500 characters)
   */
  content: string;
  /**
   * E-citizen who sent the message
   */
  ecitizen: number | Ecitizen;
  /**
   * The live stream this message belongs to
   */
  stream: number | LiveStream;
  /**
   * Type of message
   */
  type: 'user' | 'system' | 'moderator';
  /**
   * Soft delete timestamp - set by moderators
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Live stream viewer sessions and analytics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stream-views".
 */
export interface LiveStreamView {
  id: number;
  /**
   * Unique session identifier (UUID generated on client)
   */
  sessionId: string;
  /**
   * The live stream being viewed
   */
  stream: number | LiveStream;
  /**
   * Authenticated user (if logged in)
   */
  ecitizen?: (number | null) | Ecitizen;
  /**
   * Display name for anonymous viewers or authenticated user name
   */
  viewerName?: string | null;
  /**
   * Viewer IP address (for analytics)
   */
  ipAddress?: string | null;
  /**
   * Browser/device user agent
   */
  userAgent?: string | null;
  /**
   * Detected device type
   */
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
  /**
   * Country from IP geolocation (optional)
   */
  country?: string | null;
  /**
   * Video quality selected (e.g., 1080p, 720p, auto)
   */
  quality?: string | null;
  /**
   * When the viewer joined the stream
   */
  startedAt: string;
  /**
   * When the viewer left the stream
   */
  endedAt?: string | null;
  /**
   * Last time we received a heartbeat from this session
   */
  lastHeartbeatAt?: string | null;
  /**
   * Total watch time in seconds (calculated on session end)
   */
  watchDurationSeconds?: number | null;
  /**
   * Whether this session is currently active (receiving heartbeats)
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts".
 */
export interface Transcript {
  id: number;
  stream: number | LiveStream;
  language: string;
  /**
   * Monotonically increasing version of this transcript.
   */
  version: number;
  /**
   * Mark when no further live updates will be applied.
   */
  isFinal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcript-segments".
 */
export interface TranscriptSegment {
  id: number;
  transcript: number | Transcript;
  startMs: number;
  endMs: number;
  text: string;
  /**
   * Per-segment revision counter.
   */
  rev: number;
  /**
   * Set when this segment is no longer expected to change.
   */
  isStable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-chunks".
 */
export interface AudioChunk {
  id: number;
  stream: number | LiveStream;
  startMs: number;
  endMs: number;
  /**
   * Path or URL to the analysis chunk audio file.
   */
  filePath: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'ecitizen';
        value: number | Ecitizen;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'live-streams';
        value: number | LiveStream;
      } | null)
    | ({
        relationTo: 'live-chat';
        value: number | LiveChat;
      } | null)
    | ({
        relationTo: 'live-stream-views';
        value: number | LiveStreamView;
      } | null)
    | ({
        relationTo: 'transcripts';
        value: number | Transcript;
      } | null)
    | ({
        relationTo: 'transcript-segments';
        value: number | TranscriptSegment;
      } | null)
    | ({
        relationTo: 'audio-chunks';
        value: number | AudioChunk;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecitizen_select".
 */
export interface EcitizenSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  videoId?: T;
  title?: T;
  description?: T;
  duration?: T;
  date?: T;
  category?: T;
  resolutions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-streams_select".
 */
export interface LiveStreamsSelect<T extends boolean = true> {
  streamKey?: T;
  title?: T;
  description?: T;
  date?: T;
  startedAt?: T;
  visibility?: T;
  status?: T;
  endingStatus?: T;
  transcriptionEnabled?: T;
  transcriptionLanguage?: T;
  translationLanguages?: T;
  rtmpUrl?: T;
  masterPlaylistUrl?: T;
  thumbnailUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-chat_select".
 */
export interface LiveChatSelect<T extends boolean = true> {
  content?: T;
  ecitizen?: T;
  stream?: T;
  type?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stream-views_select".
 */
export interface LiveStreamViewsSelect<T extends boolean = true> {
  sessionId?: T;
  stream?: T;
  ecitizen?: T;
  viewerName?: T;
  ipAddress?: T;
  userAgent?: T;
  deviceType?: T;
  country?: T;
  quality?: T;
  startedAt?: T;
  endedAt?: T;
  lastHeartbeatAt?: T;
  watchDurationSeconds?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts_select".
 */
export interface TranscriptsSelect<T extends boolean = true> {
  stream?: T;
  language?: T;
  version?: T;
  isFinal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcript-segments_select".
 */
export interface TranscriptSegmentsSelect<T extends boolean = true> {
  transcript?: T;
  startMs?: T;
  endMs?: T;
  text?: T;
  rev?: T;
  isStable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-chunks_select".
 */
export interface AudioChunksSelect<T extends boolean = true> {
  stream?: T;
  startMs?: T;
  endMs?: T;
  filePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}