"""
Tumor Detection Utilities Module
=================================

Provides utility functions for tumor detection workflows in medical imaging.

This module contains functions for managing tumor detection sample images,
downloading reference datasets, and legacy detection implementations.

Key Features:
    - Sample image management and downloads
    - Reference image URL registry
    - Dataset preparation utilities
    - Legacy detection functions (deprecated)

Note:
    This module is primarily for backwards compatibility. New implementations
    should use the handlers module and DetectionWorker class.

Author: Aarti S Ravikumar
License: MIT
Version: 2.0.0
"""

from typing import List, Tuple, Optional
import os
import logging
import urllib.request
import subprocess
from pathlib import Path
from PyQt6.QtGui import QPixmap

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

logger = logging.getLogger(__name__)


# ============================================================================
# CONSTANTS
# ============================================================================

# Reference image URLs for demonstration/testing
# These are publicly available medical imaging examples
SAMPLE_IMAGE_URLS = {
    'axial': 'https://prod-images-static.radiopaedia.org/images/5651/b510dc0d5cd3906018c4dd49b98643_gallery.jpeg',
    'coronal': 'https://www.mriclinicalcasemap.philips.com/content/images/cases/case154/thumbs/14.jpg',
    'sagittal': 'https://prod-images-static.radiopaedia.org/images/4440984/10a4749375e20983b677e0502a9d7f_gallery.jpg'
}

# Expected detection output paths (legacy)
LEGACY_DETECTION_PATHS = [
    'runs/detect/exp2/b510dc0d5cd3906018c4dd49b98643_gallery.jpeg',
    'runs/detect/exp3/14.jpg',
    'runs/detect/exp4/10a4749375e20983b677e0502a9d7f_gallery.jpg'
]

# Local storage paths
TUMORS_DIR = 'tumors'
ORIGINALS_DIR = 'tumors/originals'

# Download settings
DOWNLOAD_TIMEOUT = 30  # seconds
MAX_RETRIES = 3


# ============================================================================
# IMAGE DATASET MANAGEMENT
# ============================================================================

def get_tumor_detection_images() -> List[Tuple[str, str]]:
    """
    Get paths to tumor detection image pairs (original, detected).
    
    Downloads sample images if not present locally and returns paths to
    both original and detected versions for demo/testing purposes.
    
    Returns:
        List of tuples: [(original_path, detected_path), ...]
            - original_path: Local path to original medical image
            - detected_path: Expected path to detection result
    
    Side Effects:
        - Downloads images from SAMPLE_IMAGE_URLS if not present
        - Creates local files in tumors/ directory
        - Logs download progress and errors
    
    Directory Structure:
        tumors/
            original_1.jpg  # Axial view
            original_2.jpg  # Coronal view
            original_3.jpg  # Sagittal view
    
    Note:
        Detected images should be generated by the detection pipeline.
        This function only provides the expected output paths.
    
    Example:
        >>> pairs = get_tumor_detection_images()
        >>> for orig, det in pairs:
        ...     print(f"Original: {orig}, Detected: {det}")
    
    Warning:
        This function is deprecated. Use the UI handlers for production.
        Provided for backwards compatibility and demo purposes only.
    """
    logger.info("Preparing tumor detection image dataset")
    
    # Ensure tumors directory exists
    _ensure_directory_exists(TUMORS_DIR)
    
    # Download original images if not present
    local_originals = []
    urls = [
        SAMPLE_IMAGE_URLS['axial'],
        SAMPLE_IMAGE_URLS['coronal'],
        SAMPLE_IMAGE_URLS['sagittal']
    ]
    
    for idx, url in enumerate(urls, start=1):
        local_path = os.path.join(TUMORS_DIR, f'original_{idx}.jpg')
        
        if not os.path.exists(local_path):
            success = _download_image(url, local_path)
            if not success:
                logger.warning(
                    f"Failed to download image {idx}, using placeholder path"
                )
        
        local_originals.append(local_path)
    
    # Pair with expected detection output paths
    image_pairs = list(zip(local_originals, LEGACY_DETECTION_PATHS))
    
    logger.info(f"Prepared {len(image_pairs)} image pairs")
    return image_pairs


# ============================================================================
# LEGACY DETECTION FUNCTIONS (DEPRECATED)
# ============================================================================

def run_axial_detection(self) -> None:
    """
    Run tumor detection on axial view image (DEPRECATED).
    
    Legacy function for running detection on a hardcoded axial view image.
    Directly runs YOLOv5 detection and updates UI.
    
    Args:
        self: UI window instance with tumor_detected_labels attribute
    
    Side Effects:
        - Runs YOLOv5 subprocess
        - Updates self.tumor_detected_labels[0] with result
        - Shows error message in label if detection fails
    
    Deprecation:
        This function is deprecated. Use run_tumor_detection() from
        handlers module instead, which provides:
            - Multi-view support (axial/coronal/sagittal)
            - Better error handling
            - User-selected images (not hardcoded)
            - Temporary file management
            - Comprehensive logging
    
    Legacy Behavior:
        - Uses hardcoded image URL
        - Uses hardcoded model path
        - Limited error handling
        - No cleanup of temp files
    
    Example (deprecated):
        >>> run_axial_detection(window)  # Don't use this
        
    Replacement:
        >>> from tumors.handlers import run_tumor_detection
        >>> run_tumor_detection(window, idx=0)  # Use this instead
    """
    logger.warning(
        "run_axial_detection() is deprecated. "
        "Use run_tumor_detection() from handlers module."
    )
    
    # Hardcoded detection parameters (legacy)
    try:
        import yolov5
        logger.info("Running legacy axial detection using yolov5 PyPI API")
        model = yolov5.load("output_models/tumor_detector_axial.pt")
        results = model(SAMPLE_IMAGE_URLS['axial'], size=640, conf=0.4)
        results.save()
        # Detected image is saved by yolov5 API; further logic can be added here if needed
        detected_path = LEGACY_DETECTION_PATHS[0]
        
        if os.path.exists(detected_path):
            pixmap = QPixmap(detected_path)
            
            if not pixmap.isNull():
                self.tumor_detected_labels[0].setPixmap(pixmap)
                logger.info(f"Loaded detection result: {detected_path}")
            else:
                _show_detection_error(
                    self,
                    0,
                    "Failed to load detection result image"
                )
        else:
            _show_detection_error(
                self,
                0,
                "Detection output file not found"
            )
            
    except subprocess.TimeoutExpired:
        logger.error("Detection process timed out")
        _show_detection_error(self, 0, "Detection timed out after 60 seconds")
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Detection subprocess failed: {e}")
        _show_detection_error(self, 0, f"Detection failed: {e}")
        
    except Exception as e:
        logger.exception("Unexpected error in legacy detection")
        _show_detection_error(self, 0, f"Error: {e}")


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def _ensure_directory_exists(directory: str) -> None:
    """
    Create directory if it doesn't exist.
    
    Args:
        directory: Path to directory to create
    
    Side Effects:
        Creates directory and parent directories as needed
    """
    try:
        os.makedirs(directory, exist_ok=True)
        logger.debug(f"Ensured directory exists: {directory}")
    except Exception as e:
        logger.error(f"Failed to create directory {directory}: {e}")


def _download_image(url: str, local_path: str) -> bool:
    """
    Download an image from URL to local path.
    
    Args:
        url: Image URL to download
        local_path: Local file path to save to
    
    Returns:
        True if download successful, False otherwise
    
    Retry Logic:
        - Attempts download up to MAX_RETRIES times
        - Uses DOWNLOAD_TIMEOUT for each attempt
        - Logs all attempts and failures
    
    Error Handling:
        - Network errors: Logged and retried
        - Timeout errors: Logged and retried
        - File write errors: Logged and failed
    """
    logger.info(f"Downloading image: {url} -> {local_path}")
    
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            # Download with timeout
            urllib.request.urlretrieve(url, local_path)
            
            # Verify file was created and has content
            if os.path.exists(local_path) and os.path.getsize(local_path) > 0:
                logger.info(
                    f"Successfully downloaded: {local_path} "
                    f"({os.path.getsize(local_path)} bytes)"
                )
                return True
            else:
                logger.warning(f"Downloaded file is empty: {local_path}")
                
        except urllib.error.URLError as e:
            logger.warning(
                f"Download attempt {attempt}/{MAX_RETRIES} failed: {e}"
            )
            
        except urllib.error.HTTPError as e:
            logger.error(f"HTTP error downloading {url}: {e.code} {e.reason}")
            return False  # Don't retry HTTP errors
            
        except Exception as e:
            logger.exception(f"Unexpected error downloading {url}: {e}")
    
    logger.error(f"Failed to download after {MAX_RETRIES} attempts: {url}")
    return False


def _show_detection_error(self, idx: int, message: str) -> None:
    """
    Display detection error message in UI label.
    
    Args:
        self: UI window instance
        idx: Image slot index
        message: Error message to display
    """
    error_text = f"Detection failed:\n{message}"
    self.tumor_detected_labels[idx].setText(error_text)
    logger.error(f"Detection error for slot {idx}: {message}")


# ============================================================================
# PUBLIC API FUNCTIONS
# ============================================================================

def download_sample_images(output_dir: Optional[str] = None) -> List[str]:
    """
    Download all sample tumor detection images to a directory.
    
    Convenience function for downloading the complete sample dataset
    for demo, testing, or training purposes.
    
    Args:
        output_dir: Directory to save images (default: tumors/originals)
    
    Returns:
        List of paths to successfully downloaded images
    
    Side Effects:
        - Creates output directory if needed
        - Downloads images from SAMPLE_IMAGE_URLS
        - Logs download progress
    
    Example:
        >>> paths = download_sample_images('data/samples')
        >>> print(f"Downloaded {len(paths)} images")
    """
    if output_dir is None:
        output_dir = ORIGINALS_DIR
    
    _ensure_directory_exists(output_dir)
    
    downloaded = []
    
    for view_name, url in SAMPLE_IMAGE_URLS.items():
        filename = f"sample_{view_name}.jpg"
        local_path = os.path.join(output_dir, filename)
        
        if _download_image(url, local_path):
            downloaded.append(local_path)
    
    logger.info(
        f"Downloaded {len(downloaded)}/{len(SAMPLE_IMAGE_URLS)} sample images"
    )
    return downloaded


def get_model_path(view: str) -> str:
    """
    Get the model file path for a specific anatomical view.
    
    Args:
        view: Anatomical view name:
            - 'axial': Horizontal cross-section
            - 'coronal': Frontal plane
            - 'sagittal': Side profile
    
    Returns:
        Path to the corresponding model file
    
    Raises:
        ValueError: If view is not recognized
    
    Example:
        >>> model = get_model_path('axial')
        >>> print(model)
        tumors/output_models/tumor_detector_axial.pt
    """
    view = view.lower()
    
    model_map = {
        'axial': 'tumors/output_models/tumor_detector_axial.pt',
        'coronal': 'tumors/output_models/tumor_detector_coronal.pt',
        'sagittal': 'tumors/output_models/tumor_detector_sagittal.pt',
    }
    
    if view not in model_map:
        raise ValueError(
            f"Unknown view: {view}. "
            f"Valid options: {', '.join(model_map.keys())}"
        )
    
    return model_map[view]


def validate_model_files() -> dict:
    """
    Check if all required model files exist.
    
    Returns:
        Dictionary mapping view names to existence status:
            {'axial': True, 'coronal': False, 'sagittal': True}
    
    Example:
        >>> status = validate_model_files()
        >>> missing = [v for v, exists in status.items() if not exists]
        >>> if missing:
        ...     print(f"Missing models: {missing}")
    """
    status = {}
    
    for view in ['axial', 'coronal', 'sagittal']:
        model_path = get_model_path(view)
        status[view] = os.path.exists(model_path)
        
        if status[view]:
            logger.debug(f"Model found: {view} -> {model_path}")
        else:
            logger.warning(f"Model missing: {view} -> {model_path}")
    
    return status


# ============================================================================
# MODULE EXPORTS
# ============================================================================

__all__ = [
    'get_tumor_detection_images',
    'run_axial_detection',  # Deprecated
    'download_sample_images',
    'get_model_path',
    'validate_model_files',
]
